name: Playwright E2E Tests

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Test tag to run (e.g. @smoke, @regression, @auth, @cart)'
        required: false
        default: ''
      browser:
        description: 'Browser to test on'
        required: false
        default: 'chromium'
        type: choice
        options:
          - chromium
          - firefox
          - webkit
          - all

env:
  CI: true
  BASE_URL: ${{ secrets.BASE_URL || 'https://automationexercise.com' }}
  TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
  TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
  TEST_USER_NAME: ${{ secrets.TEST_USER_NAME }}

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run TypeScript compiler check
        run: npx tsc --noEmit

  test:
    name: Playwright Tests (${{ matrix.project }})
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        project: ${{ github.event.inputs.browser == 'all' && fromJson('["chromium", "firefox", "webkit"]') || fromJson(format('["{0}"]', github.event.inputs.browser || 'chromium')) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.project }}
      - name: Run Playwright tests
        run: |
          if [ -n "${{ github.event.inputs.test_tag }}" ]; then
            npx playwright test --project=${{ matrix.project }} --grep "${{ github.event.inputs.test_tag }}"
          else
            npx playwright test --project=${{ matrix.project }}
          fi
      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 14
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results-${{ matrix.project }}
          path: test-results/
          retention-days: 14
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: allure-results-${{ matrix.project }}
          path: allure-results/
          retention-days: 14

  smoke-tests:
    name: Smoke Tests (Chromium)
    runs-on: ubuntu-latest
    needs: lint
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium
      - name: Run smoke tests
        run: npx playwright test --project=chromium --grep @smoke
      - name: Upload smoke test report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: smoke-test-report
          path: playwright-report/
          retention-days: 7

  publish-report:
    name: Publish Test Report
    runs-on: ubuntu-latest
    needs: test
    if: ${{ !cancelled() }}
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          pattern: playwright-report-*
          merge-multiple: true
          path: merged-report
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: merged-report
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
